apiVersion: v1
kind: Service
metadata:
  name: lifesub-web-service
  namespace: dg0409-lifesub-ns
  labels:
    app: lifesub-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 18080
      protocol: TCP
      name: http
  selector:
    app: lifesub-web
